JSJ/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
]

urlpatterns += (
    url(r'^convert/', include('lazysignup.urls')),
)


# TODO: deployment of static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    #path('item/<int:pk>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('item/<slug>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('checkout/<slug>/', views.DetailView, name='checkout'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('checkout', views.CheckoutView.as_view(), name='checkout'),
    path('payment', views.PaymentView.as_view(), name='payment'),
    path('config/', views.stripe_config),  # Stripe config
    path('create-checkout-session/', views.create_checkout_session),  # Stripe session
    path('checkout_success', views.SuccessView.as_view()),  # new
    path('cancelled/', views.CancelledView.as_view()),  # new
    path('webhook/', views.stripe_webhook),  # new
]

templates/base.html
<!DOCTYPE html>
<html>

{% include 'head.html' %}

<body>
{% include 'nav.html' %}
{% block content %}
{% endblock content %}

{% include 'footer.html' %}
{% include 'js.html' %}
</body>

</html>

templates/cancelled.html
<!-- templates/cancelled.html -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django + Stripe Checkout</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p>Your payment was cancelled.</p>
    </div>
  </section>
  </body>
</html>

templates/checkout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Oranienbaum">
    <title>JS Jewelry</title>
    <link href="style.css" rel="stylesheet">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>


<body>
<nav class="navbar navbar-expand-md navbar-white fixed-top d-flex flex-row my-flex-container-brand justify-content-between">
    <div class="p-2 flex-even"></div>
    <div class="p-2 flex-even">
        <a class="navbar-brand" href="#">JSJ</a>
    </div>
    <div class="p-2 flex-even">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">NECKLACES<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">RING</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">SHOPPING BAG(0)</a>
                </li>
            </ul>

        </div>
    </div>
</nav>


<!-- headline animation !-->

    <div class="container checkout-container">
  <div class="py-5 text-center">



        <div class="p-2">SHIPPING AND PAYMENT</div>

  </div>

  <div class="row">
    <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-primary badge-pill">3</span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Product name</h6>
            <small class="text-muted">Brief description</small>
          </div>
          <span class="text-muted money">$12</span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Second product</h6>
            <small class="text-muted">Brief description</small>
          </div>
          <span class="text-muted money">$8</span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Third item</h6>
            <small class="text-muted">Brief description</small>
          </div>
          <span class="text-muted money">$5</span>
        </li>

        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong class="money">$20</strong>
        </li>
      </ul>
    </div>

    <div class="col-md-8 order-md-1">
      <h1 class="mb-3">Billing address</h1>
      <form class="needs-validation" novalidate>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="email">Email </label>
          <input type="email" class="form-control" id="email" placeholder="you@example.com" required>
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="mb-3">
          <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
          <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
        </div>

        <div class="row">
          <div class="col-md-5 mb-3">
            <label for="country">Country</label>
            <select class="custom-select d-block w-100" id="country" required>
              <option value="">Choose...</option>
              <option>United States</option>
            </select>
            <div class="invalid-feedback">
              Please select a valid country.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="state">State</label>
            <select class="custom-select d-block w-100" id="state" required>
              <option value="">Choose...</option>
              <option>California</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid state.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zip">Zip</label>
            <input type="text" class="form-control" id="zip" placeholder="" required>
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="same-address">
          <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
        </div>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="save-info">
          <label class="custom-control-label" for="save-info">Save this information for next time</label>
        </div>
        <hr class="mb-4">

        <h4 class="mb-3">Payment</h4>

        <div class="d-block my-3">
          <div class="custom-control custom-radio">
            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
            <label class="custom-control-label" for="credit">Credit card</label>
          </div>
          <div class="custom-control custom-radio">
            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
            <label class="custom-control-label" for="debit">Debit card</label>
          </div>
          <div class="custom-control custom-radio">
            <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
            <label class="custom-control-label" for="paypal">PayPal</label>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="cc-name">Name on card</label>
            <input type="text" class="form-control" id="cc-name" placeholder="" required>
            <small class="text-muted">Full name as displayed on card</small>
            <div class="invalid-feedback">
              Name on card is required
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="cc-number">Credit card number</label>
            <input type="text" class="form-control" id="cc-number" placeholder="" required>
            <div class="invalid-feedback">
              Credit card number is required
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-3">
            <label for="cc-expiration">Expiration</label>
            <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
            <div class="invalid-feedback">
              Expiration date required
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="cc-cvv">CVV</label>
            <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
            <div class="invalid-feedback">
              Security code required
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
      </form>
    </div>
  </div>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2019-2020 JS Jewelry</p>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script>window.jQuery || document.write('<script src="assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="assets/dist/js/bootstrap.bundle.min.js"></script>
<script src="form-validation.js"></script>

<!-- footline !-->
<div class="footer-line"></div>
<footer class="container">

    <div class="row">
        <div class="col-6 col-md">
            <h5>CONTACT</h5>
        </div>
        <div class="col-6 col-md">
            <h5>SHIPPING AND RETURNING</h5>
        </div>
        <div class="col-6 col-md">
            <h5>TERMS AND CONDITIONS</h5>
        </div>
        <div class="col-6 col-md">
            <h5>SIZE GUIDE</h5>
        </div>
    </div>
</footer>

<script src="./animation.js"></script>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container d-flex flex-row">
    <div class="p-2"> Ring</div>
    <div class="p-2"> ></div>
    <div class="p-2"> Product Name</div>
</div>

<main role="main" class="container detail-body">
    <div class="row">
        <div class="col-md-6 blog-main">


            <div class="blog-post">
                <img src="{% static 'image/r1.jpg' %}" alt="ring 1">
            </div><!-- /.blog-post -->


        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
            <div class="p-4 mb-3 bg-light rounded">
                <h4 class="font-italic"> {{ item.title }}</h4>
                <p class="mb-0"> Here is a bunch of product description that
                keeps talking about how great and how awesome the product is please
                buy buy buy</p>
            </div>

            <div class="p-4">
                <h4 class="font-italic">Limited-edition</h4>
                <ol class="list-unstyled mb-0">
                    <li><p1 class="money"> $ {{ item.price }}</p1></li>
                    <li><button type="button" class="btn btn-outline-dark">Add to Cart</button></li>


                </ol>
            </div>


        </aside><!-- /.blog-sidebar -->

    </div><!-- /.row -->

</main><!-- /.container -->


<script src="./animation.js"></script>
</body>


{% endblock content %}

templates/footer.html
<!-- footline !-->

<div class="my_nav">
<div class="footer-line"></div>


<div class="container" style="background-color: white;">
    <div class="row">
        <div class="col-6 col-md">
            <a href="#">CONTACT</a>
        </div>
        <div class="col-6 col-md">
            <a href="#">SHIPPING AND RETURNING</a>
        </div>
        <div class="col-6 col-md">
            <a href="#">TERMS AND CONDITIONS</a>
        </div>
        <div class="col-6 col-md">
            <a href="#">SIZE GUIDE</a>
        </div>
    </div>
</div>
</div>

templates/head.html
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>JS Jewelry</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oranienbaum">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% if messages %}
    {% for message in messages %}
        <div class="alert .h-100 alert-{{messages.tag}}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block content %}

<!-- headline animation !-->
<div class="animation-container">
    <div class="item has-content">
        <div class="item-inner">
            <h2 class="section-title"><span>JS Jewelry</span></h2>
            <div class="outer-content">
                <p>With more than 25 years of craftsmanship we promise to deliver to you the ring you've been looking
                    for! </p>
            </div>
            <p class="more-btn">See Collection</p>
        </div>
    </div>

    <div class="item main-img">
        <div class="display">
            <figure class="trainers">
                <img src="https://purepng.com/public/uploads/medium/purepng.com-diamond-ringclothingdiamond-ringfashion-jewelry-ring-stone-love-wedding-object-gold-accessory-diamond-jewel-marriage-relationship-wed-marry-jewellery-631522327134itrf8.png">
        </div>

        <div class="bg"></div>
    </div>
</div>


<!-- item content row 1!-->

<div class="d-flex flex-row flex-wrap content-container">
    {% for item in object_list  %}
    <div class=" pt-2 px-2 pt-3 px-3 text-center col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <div class="my-1 py-1">
            <div class="item-listing">
                <div class="listing-children">
                    <img src="{{ item.item_picture.url }}" alt="{{ item.title }}">
                </div>
                <div class="listing-children">
                    <p class="item-description"> {{ item.title }} </p>

                    <a class="item-price effect-underline" href="{{ item.get_absolute_url }}"> ${{ item.price }} </a>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
<div class="d-flex flex-row flex-wrap content-container home-content-padding"></div>

<script src="{% static 'js/animation.js' %}"></script>

{% endblock content %}

templates/js.html
{% load static %}
    <!-- avaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>window.jQuery || document.write('<script src="assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/form-validation.js' %}"></script>

templates/nav.html
{% load cart_template_tags %}

<nav class="navbar navbar-expand-md navbar-white fixed-top d-flex flex-row my-flex-container-brand justify-content-between">
    <div class="p-2 flex-even"></div>
    <div class="p-2 flex-even">
        <a class="navbar-brand" href="{% url 'core:home' %}">JSJ</a>
    </div>
    <div class="p-2 flex-even">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link effect-underline" href="{% url 'core:order-summary'%}" >SHOPPING BAG({{ request.user|cart_item_count }})</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link effect-underline" href="{% url 'logout'%}">LOGOUT</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link effect-underline" href="{% url 'login'%}">LOGIN</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <strong> <a class="nav-link effect-underline" href="{% url 'register'%}">SIGN UP<span class="sr-only">(current)</span></a></strong>
                </li>
            </ul>

        </div>
    </div>
</nav>

templates/success.html
<!-- templates/success.html -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django + Stripe Checkout</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p>Your payment succeeded.</p>
    </div>
  </section>
  </body>
</html>